name: .NET 5

on: [push, workflow_dispatch]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.201
    - name: Test with dotnet
      run: dotnet test Bsii.Dotnet.Utils.Tests/Bsii.Dotnet.Utils.Tests.csproj
